sudo: required
services:
  - docker

before_install:
  - docker build -t erickmckracken/docker-react -f Dockerfile.dev .


script:
  - docker run erickmckracken/docker-react npm run test -- --coverage